# Follow the makefile naming conventions and ordering where possible.
# Many variables have duplicate file listings which had to be removed
# for input into Bazel rules.

EXTRA_DIST = [
    "alloca.h",
    "allocator.h",
    "argmatch.h",
    # "assert.h",
    "verify.h",
    "assure.h",
    "attribute.h",
    "basename-lgpl.h",
    "file-type.h",
    "c-strcase.h",
    "c-strcaseeq.h",
    "c32is-impl.h",
    "c32to-impl.h",
    "calloc.c",
    "careadlinkat.h",
    "chdir-long.h",
    "cloexec.h",
    "dirent-private.h",
    "ctype.h",
    "dirent.h",
    "stripslash.c",
    "dirname.h",
    # "errno.h",
    "error.h",
    "exclude.h",
    "exitfail.h",
    "fcntl.h",
    "fd-hook.h",
    "filename.h",
    "filenamecat.h",
    "flexmember.h",
    "fnmatch_loop.c",
    "fnmatch.c",
    # "fnmatch.h",
    "fopen.c",
    "at-func.c",
    "getlocalename_l-unsafe.h",
    # "getopt-cdefs.h",
    "getopt-core.h",
    "getopt-ext.h",
    "getopt-pfx-core.h",
    "getopt-pfx-ext.h",
    # "getopt.h",
    "getopt_int.h",
    "getprogname.h",
    "dynarray.h",
    "malloc/dynarray-skeleton.c",
    "malloc/dynarray.h",
    "hard-locale.h",
    "hash.h",
    "ialloc.h",
    "ignore-value.h",
    "intprops-internal.h",
    "intprops.h",
    "inttypes.h",
    "iswctype-impl.h",
    "langinfo.h",
    "cdefs.h",
    "libc-config.h",
    "limits.h",
    "localcharset.h",
    "locale.h",
    "localename.h",
    "malloc.c",
    "malloca.h",
    "lc-charset-dispatch.c",
    "lc-charset-dispatch.h",
    "mbrtowc-impl.h",
    "mbtowc-lock.c",
    "mbtowc-lock.h",
    "windows-initguard.h",
    "mbrtowc-impl-utf8.h",
    "mbsrtoc32s-state.c",
    "mbsrtowcs-impl.h",
    "mbsrtowcs-state.c",
    "mbtowc-impl.h",
    "mktime-internal.h",
    "mktime.c",
    "msvc-inval.h",
    "msvc-nothrow.h",
    "strftime.c",
    "strftime.h",
    "openat.h",
    "pathmax.h",
    "pthread.h",
    "quote.h",
    "quotearg.h",
    "regcomp.c",
    "regex.h",
    "regex_internal.c",
    "regex_internal.h",
    "regexec.c",
    "save-cwd.h",
    "sched.h",
    "setlocale_null.h",
    "sig-handler.h",
    "signal.h",
    "sigsegv.h",
    "stackvma.h",
    "_Noreturn.h",
    "arg-nonnull.h",
    "c++defs.h",
    "warn-on-use.h",
    "stat-w32.c",
    "stat-w32.h",
    "stat-macros.h",
    "stat-size.h",
    "stat-time.h",
    # "stdarg.h",
    # "stdbit.h",
    "stdckdint.h",
    "stddef.h",
    # "stdint.h",
    "stdio.h",
    "stdlib.h",
    "stdopen.h",
    "streq.h",
    "strerror-override.h",
    "string.h",
    "strings.h",
    "strtol.c",
    # "sys_random.h",
    # "sys_stat.h",
    # "sys_time.h",
    # "sys_types.h",
    # "sys_wait.h",
    "tempname.h",
    "time.h",
    "time-internal.h",
    "timespec.h",
    "uchar.h",
    "unicase.h",
    "unicase/simple-mapping.h",
    "unicase/tolower.h",
    "unictype.h",
    "unictype/bitmap.h",
    "unictype/ctype_alnum.h",
    "unictype/ctype_alpha.h",
    "unictype/ctype_blank.h",
    "unictype/ctype_cntrl.h",
    "unictype/ctype_digit.h",
    "unictype/ctype_graph.h",
    "unictype/ctype_lower.h",
    "unictype/ctype_print.h",
    "unictype/ctype_punct.h",
    "unictype/ctype_space.h",
    "unictype/ctype_upper.h",
    "unictype/ctype_xdigit.h",
    "uninorm.h",
    "unistd.h",
    "unistr.h",
    "unistr/u-cpy.h",
    "unistr/u-pcpy.h",
    "unistr/u-strcat.h",
    "unistr/u-strlen.h",
    "unitypes.h",
    "uniwidth.h",
    "uniwidth/cjk.h",
    "uniwidth/width0.h",
    "uniwidth/width2.h",
    "unlocked-io.h",
    "wchar.h",
    "wctype-impl.h",
    "wctype.h",
    "windows-mutex.h",
    "windows-once.h",
    "windows-recmutex.h",
    "windows-rwlock.h",
    "wmemchr-impl.h",
    "xalloc.h",
    "xalloc-oversized.h",
    "xmalloca.h",
    "xstdopen.h",
    "xstrtol.h",
]

BUILT_SOURCES = [
    "alloca.h",
    # "assert.h",
    "ctype.h",
    "dirent.h",
    # "errno.h",
    "error.h",
    "fcntl.h",
    # "fnmatch.h",
    # "getopt.h",
    # "getopt_cdefs.h",
    "malloc/dynarray.gl.h",
    "malloc/dynarray-skeleton.gl.h",
    "inttypes.h",
    "langinfo.h",
    "limits.h",
    "locale.h",
    "pthread.h",
    "sched.h",
    "signal.h",
    "sigsegv.h",
    # "stdarg.h",
    # "stdbit.h",
    "stdckdint.h",
    "stddef.h",
    # "stdint.h",
    "stdio.h",
    "stdlib.h",
    "string.h",
    "strings.h",
    "sys/random.h",
    "sys/stat.h",
    "sys/time.h",
    "sys/types.h",
    "sys/wait.h",
    "time.h",
    "uchar.h",
    "unicase.h",
    "unictype.h",
    "uninorm.h",
    "unistd.h",
    "unistr.h",
    "unitypes.h",
    "uniwidth.h",
    "wchar.h",
    "wctype.h",
]

# libdiffutils_a_SOURCES
SOURCES = [
    "allocator.c",
    "argmatch.c",
    "openat-priv.h",
    "openat-proc.c",
    "basename-lgpl.c",
    "binary-io.h",
    "binary-io.c",
    "bitrotate.h",
    "bitrotate.c",
    "btoc32.c",
    # "btow.c",
    "c-ctype.h",
    "c-ctype.c",
    "c-file-type.c",
    "c-stack.h",
    "c-stack.c",
    "c-strcasecmp.c",
    "c32_apply_type_test.c",
    "c32_get_type_test.c",
    "c32isalnum.c",
    "c32isalpha.c",
    "c32isblank.c",
    "c32iscntrl.c",
    "c32isdigit.c",
    "c32isgraph.c",
    "c32islower.c",
    "c32isprint.c",
    "c32ispunct.c",
    "c32isspace.c",
    "c32isupper.c",
    "c32isxdigit.c",
    "c32tolower.c",
    "c32width.c",
    "careadlinkat.c",
    "chdir-long.c",
    "cloexec.c",
    "diffseq.h",
    "dirname.c",
    "basename.c",
    "dirname-lgpl.c",
    "stripslash.c",
    "exclude.c",
    "exitfail.c",
    "fcntl.c",
    "fd-hook.c",
    "filenamecat.c",
    "filenamecat-lgpl.c",
    "getprogname.c",
    "gettext.h",
    "gettime.c",
    "malloc/dynarray_at_failure.c",
    "malloc/dynarray_emplace_enlarge.c",
    "malloc/dynarray_finalize.c",
    "malloc/dynarray_resize.c",
    "malloc/dynarray_resize_clear.c",
    "hard-locale.c",
    "hash.c",
    "ialloc.c",
    "idx.h",
    "localcharset.c",
    "glthread/lock.h",
    "glthread/lock.c",
    "malloca.c",
    "mbrtoc32.c",
    "mbrtowc.c",
    "mbscasecmp.c",
    "mbsrtoc32s.c",
    "mbsrtowcs.c",
    "mbszero.c",
    "mcel.c",
    "mcel.h",
    "minmax.h",
    "nl_langinfo.c",
    "nstrftime.c",
    "glthread/once.h",
    "glthread/once.c",
    "openat-die.c",
    "progname.h",
    "progname.c",
    "propername-lite.c",
    "propername.h",
    "quotearg.c",
    "realloc.c",
    "reallocarray.c",
    "same-inode.h",
    "same-inode.c",
    "save-cwd.c",
    "setlocale_null.c",
    "setlocale_null-unlocked.c",
    "sh-quote.h",
    "sh-quote.c",
    "sig-handler.c",
    "sigsegv.c",
    "stackvma.c",
    "stat-time.c",
    "stdlib.c",
    "stdopen.c",
    "strnlen1.h",
    "strnlen1.c",
    "system-quote.h",
    "system-quote.c",
    "tempname.c",
    "glthread/threadlib.c",
    "time_rz.c",
    "timespec.c",
    "unicase/tolower.c",
    "unictype/ctype_alnum.c",
    "unictype/ctype_alpha.c",
    "unictype/ctype_blank.c",
    "unictype/ctype_cntrl.c",
    "unictype/ctype_digit.c",
    "unictype/ctype_graph.c",
    "unictype/ctype_lower.c",
    "unictype/ctype_print.c",
    "unictype/ctype_punct.c",
    "unictype/ctype_space.c",
    "unictype/ctype_upper.c",
    "unictype/ctype_xdigit.c",
    "unistd.c",
    "unistr/u32-chr.c",
    "unistr/u32-cpy.c",
    "unistr/u32-pcpy.c",
    "unistr/u32-strcat.c",
    "unistr/u32-strlen.c",
    "uniwidth/width.c",
    "version-etc.h",
    "version-etc.c",
    "version-etc-fsf.c",
    "wctype-h.c",
    "xmalloc.c",
    "xalloc-die.c",
    "xfreopen.c",
    "xfreopen.h",
    "xmalloca.c",
    "xstdopen.c",
    "xstrtoimax.c",
    "xstrtol.c",
    "xstrtoul.c",
    "cmpbuf.c",
    "diagnose.c",
]

EXTRA_libdiffutils_a_SOURCES = [
    # "calloc.c",
    # "fnmatch.c",
    # "fnmatch_loop.c",
    "fopen.c",
    # "at-func.c",
    # "malloc/dynarray-skeleton.c",
    # "malloc.c",
    # "lc-charset-dispatch.c",
    # "mbtowc-lock.c",
    # "mbsrtoc32s-state.c",
    # "mbsrtowcs-state.c",
    # "mktime.c",
    # "strftime.c",
    # "regcomp.c",
    # "regex_internal.c",
    # "regexec.c",
    # "stat-w32.c",
    # "strtol.c",
]

noinst_HEADERS = [
    "cmpbuf.h",
    "diagnose.h",
]

cc_library(
    name = "diffutils-fopen",
    srcs = [
        "fopen.c",
        "config.h",
        "stdio.h",
        "fcntl.h",
        "unistd.h",
        "sys/types.h",
        "sys/stat.h",
    ],
    includes = ["."]
)

cc_library(
    name = "diffutils",
    srcs = BUILT_SOURCES + SOURCES + noinst_HEADERS +
    # EXTRA_libdiffutils_a_SOURCES +
    # [ "fopen.c", "fcntl.c" ] +
    [
        "config.h",
    ],
    deps = [
        ":diffutils-fopen"
    ],
    hdrs = EXTRA_DIST,
    textual_hdrs = ["xstrtol.c"],
    includes = ["."],
    visibility = ["//src:__subpackages__"]
)


# cc_library(
#   name = "diffutils",
#   srcs = [
#       "config.h",
#   ] + glob(["**/*.c"], ["fnmatch_loop.c", "xstrtol.c"]),
#   # deps = [":config"],
#   hdrs = glob(["**/*.h"], ["config.h"]),
#   includes = ["./"],
#   textual_hdrs = ["fnmatch_loop.c", "xstrtol.c"],
#   visibility = ["//src:__subpackages__"],
#   # defines = ["_GL_CONFIG_H_INCLUDED"]
#   # alwayslink = True,
# )

# cc_library(
#     name = "config",
#     hdrs = ["config.h"],
#     visibility = ["//src:__subpackages__"],
# )
