# Follow the makefile naming conventions and ordering where possible.
# Many variables have duplicate file listings which had to be removed
# for input into Bazel rules.

EXTRA_DIST = [
    "alloca.h",
    "allocator.h",
    "argmatch.h",
    "assert.h",
    "verify.h",
    "assure.h",
    "attribute.h",
    "basename-lgpl.h",
    "file-type.h",
    "c-strcase.h",
    "c-strcaseeq.h",
    "c32is-impl.h",
    "c32to-impl.h",
    "calloc.c",
    "careadlinkat.h",
    "chdir-long.h",
    "cloexec.h",
    "dirent-private.h",
    "ctype.h",
    "dirent.h",
    "stripslash.c",
    "dirname.h",
    "errno.h",
    "error.h",
    "exclude.h",
    "exitfail.h",
    "fcntl.h",
    "fd-hook.h",
    "filename.h",
    "filenamecat.h",
    "flexmember.h",
    "fnmatch_loop.c",
    "fnmatch.c",
    "fnmatch.h",
    "fopen.c",
    "at-func.c",
    "getlocalename_l-unsafe.h",
    "getopt-cdefs.h",
    "getopt-core.h",
    "getopt-ext.h",
    "getopt-pfx-core.h",
    "getopt-pfx-ext.h",
    "getopt.h",
    "getopt_int.h",
    "getprogname.h",
    "dynarray.h",
    "malloc/dynarray-skeleton.c",
    "malloc/dynarray.h",
    "hard-locale.h",
    "hash.h",
    "ialloc.h",
    "ignore-value.h",
    "intprops-internal.h",
    "intprops.h",
    "inttypes.h",
    "iswctype-impl.h",
    "langinfo.h",
    "cdefs.h",
    "libc-config.h",
    "limits.h",
    "localcharset.h",
    "locale.h",
    "localename.h",
    "malloc.c",
    "malloca.h",
    "lc-charset-dispatch.c",
    "lc-charset-dispatch.h",
    "mbrtowc-impl.h",
    "mbtowc-lock.c",
    "mbtowc-lock.h",
    "windows-initguard.h",
    "mbrtowc-impl-utf8.h",
    "mbsrtoc32s-state.c",
    "mbsrtowcs-impl.h",
    "mbsrtowcs-state.c",
    "mbtowc-impl.h",
    "mktime-internal.h",
    "mktime.c",
    "msvc-inval.h",
    "msvc-nothrow.h",
    "strftime.c",
    "strftime.h",
    "openat.h",
    "pathmax.h",
    "pthread.h",
    "quote.h",
    "quotearg.h",
    "regcomp.c",
    "regex.h",
    "regex_internal.c",
    "regex_internal.h",
    "regexec.c",
    "save-cwd.h",
    "sched.h",
    "setlocale_null.h",
    "sig-handler.h",
    "signal.h",
    "sigsegv.h",
    "stackvma.h",
    "_Noreturn.h",
    "arg-nonnull.h",
    "c++defs.h",
    "warn-on-use.h",
    "stat-w32.c",
    "stat-w32.h",
    "stat-macros.h",
    "stat-size.h",
    "stat-time.h",
    "stdarg.h",
    "stdbit.h",
    "stdckdint.h",
    "stddef.h",
    "stdint.h",
    "stdio.h",
    "stdlib.h",
    "stdopen.h",
    "streq.h",
    "strerror-override.h",
    "string.h",
    "strings.h",
    "strtol.c",
    "sys_random.h",
    "sys_stat.h",
    "sys_time.h",
    "sys_types.h",
    "sys_wait.h",
    "tempname.h",
    "time.h",
    "time-internal.h",
    "timespec.h",
    "uchar.h",
    "unicase.h",
    "unicase/simple-mapping.h",
    "unicase/tolower.h",
    "unictype.h",
    "unictype/bitmap.h",
    "unictype/ctype_alnum.h",
    "unictype/ctype_alpha.h",
    "unictype/ctype_blank.h",
    "unictype/ctype_cntrl.h",
    "unictype/ctype_digit.h",
    "unictype/ctype_graph.h",
    "unictype/ctype_lower.h",
    "unictype/ctype_print.h",
    "unictype/ctype_punct.h",
    "unictype/ctype_space.h",
    "unictype/ctype_upper.h",
    "unictype/ctype_xdigit.h",
    "uninorm.h",
    "unistd.h",
    "unistr.h",
    "unistr/u-cpy.h",
    "unistr/u-pcpy.h",
    "unistr/u-strcat.h",
    "unistr/u-strlen.h",
    "unitypes.h",
    "uniwidth.h",
    "uniwidth/cjk.h",
    "uniwidth/width0.h",
    "uniwidth/width2.h",
    "unlocked-io.h",
    "wchar.h",
    "wctype-impl.h",
    "wctype.h",
    "windows-mutex.h",
    "windows-once.h",
    "windows-recmutex.h",
    "windows-rwlock.h",
    "wmemchr-impl.h",
    "xalloc.h",
    "xalloc-oversized.h",
    "xmalloca.h",
    "xstdopen.h",
    "xstrtol.h",
]

BUILT_SOURCES = [
    "fcntl.h",
    "sigsegv.h",

    "stdlib.h",
    "string.h",

    "sys/stat.h",

    "uchar.h",

    "wchar.h",
]

# libdiffutils_a_SOURCES
SOURCES = [
    "allocator.c",
    "argmatch.c",
    "openat-priv.h",
    "openat-proc.c",
    "basename-lgpl.c",
    "binary-io.h",
    "binary-io.c",
    "bitrotate.h",
    "bitrotate.c",
    "btoc32.c",
    "btowc.c",
    "c-ctype.h",
    "c-ctype.c",
    "c-file-type.c",
    "gettext.h",
    "c-stack.h",
    "c-stack.c",
    "c-strcasecmp.c",
    "c32_apply_type_test.c",

    "getprogname.c",

    "idx.h",

    "stdlib.c",
]

cc_library(
    name = "diffutils",
    srcs = BUILT_SOURCES + SOURCES + [
        "config.h",
    ],
    hdrs = EXTRA_DIST,
    includes = ["."],
)


# cc_library(
#   name = "diffutils",
#   srcs = [
#       "config.h",
#   ] + glob(["**/*.c"], ["fnmatch_loop.c", "xstrtol.c"]),
#   # deps = [":config"],
#   hdrs = glob(["**/*.h"], ["config.h"]),
#   includes = ["./"],
#   textual_hdrs = ["fnmatch_loop.c", "xstrtol.c"],
#   visibility = ["//src:__subpackages__"],
#   # defines = ["_GL_CONFIG_H_INCLUDED"]
#   # alwayslink = True,
# )

# cc_library(
#     name = "config",
#     hdrs = ["config.h"],
#     visibility = ["//src:__subpackages__"],
# )
